---
# Install Ruby
- name: Install Ruby and Bundler
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - ruby-full
    - ruby-bundler
    - build-essential
  tags: ruby
