- name: Configure DB host
  hosts: all
  become: true
  tasks:
    - name: Add keyserver
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927
    
    - name: Add repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
    
    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Enable MongoDB
      systemd:
        name: mongod
        enabled: true
